#!/bin/bash

set -e


fmt="%-30s %s\n"
time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
USER=$USER
RED='\033[0;31m'
GREEN='\033[0;32'
BLUE='\033[0;34'
NC='\033[0m' # No Color

cli_help_deploy() {
  echo "
Command: test
Usage: ./main test [path] [package-manager] [base-image]
Commands:
  path /path/to/dockerfile
  package-manager apt|pip|
  language python|node|tomcat|java
  "
  exit 1
}

base_image(){
    echo -e "\n********************************************"
    printf "${fmt}" "Checking Base Image Optimizations ..."
    echo "*************************************************"

    if [[ ! -n "$1" ]]; then
        cli_help_deploy
        echo -e "Set the base image dependancies needed for better results \n Find basic optimizations listed below"
        extra_opt
    elif [[ "$1" == "python"  ]]; then
        echo -e "Python Slim Images"
        echo -e "\t=> https://hub.docker.com/_/python/tags?page=1&name=slim \n"
        extra_opt
    elif [[ "$1" == "node" ]]; then
        echo -e "Node Slim Images"
        echo -e "\t=> https://hub.docker.com/_/node/tags?page=1&name=slim \n"      
        extra_opt
    elif [[ "$1" == "tomcat" ]]; then
        echo -e "Tomcat Slim Images"
        echo -e "\t=> https://hub.docker.com/_/tomcat/tags?page=1&name=slim \n"       
        extra_opt 
    elif [[ "$1" == "java" ]]; then
        echo -e "Java Slim Images"
        echo -e "\t=> https://hub.docker.com/_/openjdk/tags?page=1&name=slim \n"   
        extra_opt
    else
        echo -e "These specific language is not supported yet, below mentioned base images can be used instead \n"
        extra_opt
    fi
    
}

extra_opt(){
    echo -n "Few other base image that can be used \n"
    echo -e "Alpine Images"
    echo -e "\t=> https://hub.docker.com/_/alpine \n"
    echo -e "Distroless Images"
    echo -e "\t=> https://github.com/GoogleContainerTools/distroless \n"
}