#!/usr/bin/env bash
set -e

fmt="%-30s %s\n"
time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
USER=$USER
RED='\033[0;31m'
GREEN='\033[0;32'
BLUE='\033[0;34'
NC='\033[0m' # No Color

buildtest(){
    docker build -f $1 .

    if [ $? -eq 1 ]; then
        echo "${GREEN}Dockerbuild failed. Please error and make a quick fix before optimization process ...${NC}"
        exit 1
    else
        echo "Docker build passed. Optimization process starting"
        
    fi   
}