#!/bin/bash

set -e

fmt="%-30s %s\n"
time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
USER=$USER
RED='\033[0;31m'
GREEN='\033[0;32'
BLUE='\033[0;34'
NC='\033[0m' # No Color

package_cleanup(){
    echo -e "\n********************************************"
    printf "${fmt}" "Checking cleanup build parameters ..."
    echo "*************************************************"
    if [[ ${2} == "apt" ]]; then
        if  cat $1 | grep -q "^apt-get\sautoclean*" || cat $1 | grep -q "^apt-get\sautoremove*"; then
            sleep 5;
            printf "${fmt}" "Package cleanups not Found ..."
            printf "${fmt}" "Finding Optimizations ..."
            echo -e "Creation date: ${time}"
            echo -e "performed by: ${USER}\n"
            sleep 5;
            echo -e "${GREEN}APT Cleanups done. Good Job !!!${NC}"
        else
            sleep 5;
            printf "${fmt}" "Package cleanups not Found ..."
            printf "${fmt}" "Finding Optimizations ..."
            echo -e "Creation date: ${time}"
            echo -e "performed by: ${USER}\n"
            sleep 5;
            echo -e "${RED}Two Main Optmizations found${NC}"
            echo -e $BLUE"\t=> APT Package Remove - https://manpages.ubuntu.com/manpages/xenial/man8/apt.8.html#:~:text=autoremove%20(apt%2Dget(8,were%20removed%20in%20the%20meantime."${NC}
            echo -e $BLUE"\t=> APT Package Clean - https://linux.die.net/man/8/apt-get"${NC}
            sleep 2;

        fi
    elif [[ ${2} == "pip" ]]; then
        if  cat $1 | grep -q "^--no-cache-dir*" ; then
            echo "pip package manager cleanup found ..."
        else
            sleep 5;
            printf "${fmt}" "Package cleanups not Found ..."
            printf "${fmt}" "Finding Optimizations ..."
            echo -e "Creation date: ${time}"
            echo -e "performed by: ${USER}\n"
            sleep 5;
            echo -e "${RED}Two Main Optmizations found${NC}"
            echo -e "\t=> PIP cache maintain - https://pip.pypa.io/en/stable/cli/pip_cache/"
            sleep 2;
        fi       
    else
        echo "$2 package manager is not supported as of now"
    fi
}