templateFiles: "/Users/nikkitagomez/Desktop/Optimizer/docker-optimizer/templates/python/"
buildOpts:
  technology: "python"
  version: "3.7"
  codeDir: "/Users/nikkitagomez/Desktop/Optimizer/sample-app/user-service/"
  repository: "sample-app"
  tag: "v1.0.0"
  defaultDockerFileName: "Dockerfile"